export const FETCH_DOG_REQUEST = "FETCH_DOG_REQUEST";
export const FETCH_DOG_SUCCESS = "FETCH_DOG_SUCCESS";
export const FETCH_DOG_FAILURE = "FETCH_DOG_FAILURE";

export const FETCH_FOX_REQUEST = "FETCH_FOX_REQUEST";
export const FETCH_FOX_SUCCESS = "FETCH_FOX_SUCCESS";
export const FETCH_FOX_FAILURE = "FETCH_FOX_FAILURE";
